# kind: Route
# apiVersion: route.openshift.io/v1
# metadata:
#   name: {{ .Values.postgres.name }}
#   namespace: {{ .Values.namespace}}
# spec:
#   host: "{{ .Values.postgres.name }}-{{ .Values.namespace }}.apps.{{ .Values.clustername }}"
#   to:
#     kind: Service
#     name: immich-server
#     weight: 100
#   port:
#     targetPort: http
#   wildcardPolicy: None