kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.namespace }}-machine-learning
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Values.namespace }}
      app.kubernetes.io/name: machine-learning
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: {{ .Values.namespace }}
        app.kubernetes.io/name: machine-learning
    spec:
      restartPolicy: Always
      serviceAccountName: default
      schedulerName: default-scheduler
      enableServiceLinks: true
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - resources: {}
          readinessProbe:
            httpGet:
              path: /ping
              port: http
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: {{ .Values.namespace }}-machine-learning
          livenessProbe:
            httpGet:
              path: /ping
              port: http
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: DB_DATABASE_NAME
              value: {{ .Values.postgres.database.name }}
            - name: DB_HOSTNAME
              value: {{ .Values.namespace }}-{{ .Values.postgres.name }}-service
            - name: DB_PASSWORD
              value: {{ .Values.postgres.database.password }}
            - name: DB_USERNAME
              value: {{ .Values.postgres.database.username }}
            - name: IMMICH_MACHINE_LEARNING_URL
              value: 'http://{{ .Values.namespace }}-machine-learning:3003'
            - name: REDIS_HOSTNAME
              value: {{ .Values.namespace }}-{{ .Values.immichredis.name }}-service
            - name: TRANSFORMERS_CACHE
              value: /cache
          ports:
            - name: http
              containerPort: 3003
              protocol: TCP
          imagePullPolicy: IfNotPresent
          startupProbe:
            httpGet:
              path: /ping
              port: http
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 60
          volumeMounts:
            - name: cache
              mountPath: /cache
          terminationMessagePolicy: File
          image: 'ghcr.io/immich-app/immich-machine-learning:{{ .Values.image.tag }}'
      automountServiceAccountToken: true
      serviceAccount: default
      volumes:
        - name: cache
          emptyDir: {}
      dnsPolicy: ClusterFirst
  strategy:
    type: Recreate
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 600