kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: immich-route
  namespace: {{ .Values.namespace }}
spec:
  host: "web-{{ .Values.namespace }}.apps.{{ .Values.clustername }}"
  to:
    kind: Service
    name: {{ .Values.namespace }}-server
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.namespace }}-{{ .Values.postgres.name }}-service
  namespace: {{ .Values.namespace}}
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
  selector:
    app: {{ .Values.namespace }}-{{ .Values.postgres.name }}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.namespace }}-{{ .Values.immichredis.name }}-service
  namespace: {{ .Values.namespace}}
spec:
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
  selector:
    app: {{ .Values.namespace }}-{{ .Values.immichredis.name }}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.namespace }}-server
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Values.namespace }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: server
    app.kubernetes.io/service: {{ .Values.namespace }}-server
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: http
      protocol: TCP
      port: 2283
      targetPort: http
  internalTrafficPolicy: Cluster
  clusterIPs:
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app.kubernetes.io/instance: {{ .Values.namespace }}-server
    app.kubernetes.io/name: server
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.namespace }}-machine-learning
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Values.namespace }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: machine-learning
    app.kubernetes.io/service: {{ .Values.namespace }}-machine-learning
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: http
      protocol: TCP
      port: 3003
      targetPort: http
  internalTrafficPolicy: Cluster
  clusterIPs:
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app.kubernetes.io/instance: {{ .Values.namespace }}
    app.kubernetes.io/name: machine-learning
