apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.immichredis.name }}
  namespace: {{ .Values.namespace }}
spec:
  serviceName: {{ .Values.namespace }}-{{ .Values.immichredis.name }}-service
  replicas: {{ .Values.immichredis.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.immichredis.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.immichredis.name }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: {{ .Values.immichredis.name }}
          image: "{{ .Values.immichredis.image.name }}:{{ .Values.immichredis.image.tag }}"
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: {{ .Values.immichredis.name }}
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.immichredis.name }}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.immichredis.storage }}