kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: immich-db
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: immich-db
  volumeMode: Filesystem