kind: PersistentVolume
apiVersion: v1
metadata:
  name: immich-db-pv
spec:
  capacity:
    storage: 100Gi
  nfs:
    server: 192.168.69.9
    path: /mnt/Data/ocp/userdata
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: lvms-vg1
  volumeMode: Filesystem