kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: postgresql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql-db
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: postgresql-db
    spec:
      volumes:
        - name: cache-volume
          persistentVolumeClaim:
            claimName: immich-db-pvc
      containers:
        - name: postgresql-db
          image: 'docker.io/tensorchord/pgvecto-rs:pg16-v0.3.0'
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: immich-db-secret
            - name: PGDATA
              value: /mnt/data/pgdata/pg16
            - name: POSTGRESQL_DATABASE
              value: immich
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: immich-db-secret
            - name: POSTGRESQL_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: immich-db-secret
          securityContext:
            runAsUser: 3000
          resources: {}
          volumeMounts:
            - name: cache-volume
              mountPath: /mnt/data
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext:
        fsGroup: 0
      schedulerName: default-scheduler
  serviceName: postgresql-db-service
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  revisionHistoryLimit: 10
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: immich
spec:
  host: immich-mnovak-test.apps.ocp-sno.example.com
  to:
    kind: Service
    name: immich-server
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
---
kind: Secret
apiVersion: v1
metadata:
  name: immich-db-secret
data:
  password: UEBzc3cwcmQ=
  username: cG9zdGdyZXM=
type: Opaque
