kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: immich-db-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: immich-db-pv
  volumeMode: Filesystem